qdrant:
  collection_name: newsapi_news
  vector_size: 384

data_transformation:
  news_data_filename: newsapi_news_2023-11-03_to_2023-12-10.json

training_data_generation:
  examples_filename: training_examples.json
  engine: text-davinci-003
  temperature: 0
  max_tokens: 100
  prompt_template: |
    You are an expert in the IT development and edge technologies. I will give you some information about myself and you will provide me with a development advice.

    # ABOUT ME
    {ABOUT_ME}

    # CONTEXT
    {CONTEXT}

    Please provide concrete advice in less than 100 tokens, and justify your answer based on the news provided in the context.

newsapi_request:
  language: en
  sort_by: publishedAt
  page_size: 100
  page: 1

news_download:
  num_requests: 150
  from_date: 2023-11-04
  to_date: 2023-12-11
  queries_list: [
    '+Artificial Intelligence',
    '+Machine Learning',
    '+Deep Learning',
    '+Neural Networks',
    '+Blockchain Technology',
    '+Internet of Things',
    '+Cybersecurity',
    '+Cloud Computing',
    '+Quantum Computing',
    '+Augmented Reality',
    '+Virtual Reality',
    '+Data Science',
    '+Natural Language Processing',
    '+Big Data',
    '+Cryptocurrency',
    '+Computer Vision',
    '+5G Technology',
    '+Robotics',
    '+Fintech',
    '+Biotechnology',
    '+Tech Startups',
    '+E-commerce Trends',
    '+Programming Languages',
    '+Web Development',
    '+Mobile App Development',
    '+Cyber Threats',
    '+Artificial General Intelligence',
    '+Edge Computing',
    '+Smart Cities Technology',
    '+IoT Security',
    '+DevOps Practices',
    '+AR/VR Applications',
    '+Ethical AI',
    '+Drones Technology',
    '+Innovations',
    '+Adaptive Learning Systems',
    '+Cloud Security',
    '+Data Privacy Laws',
    '+Machine Translation',
    '+Digital Transformation',
    '+Autonomous Vehicles',
    '+Quantum Cryptography',
    '+AI Ethics',
    '+Smart Home Technology',
    '+Renewable Energy Tech',
    '+Genomic Technologies',
    '+Holographic Technology',
    '+AI in Healthcare',
    '+IoT in Agriculture',
    '+5G Infrastructure',
    '+Bioinformatics',
    '+AI-powered Assistants',
    '+AR/VR in Education',
    '+Cloud-native Applications',
    '+Blockchain in Supply Chain',
    '+Edge AI',
    '+AI-driven Marketing',
    '+Cybersecurity Frameworks',
    '+Fintech Regulations',
    '+Quantum Machine Learning',
    '+IoT in Manufacturing',
    '+Humanoid Robots',
    '+Smart Grid Technology',
    '+AI Chips',
    '+Ethical Hacking',
    '+Biometric Security',
    '+Data Mining Techniques',
    '+Digital Twins',
    '+Voice Recognition Technology',
    '+Agile Development Practices',
    '+Cryptocurrency Regulations',
    '+AI-powered Chatbots',
    '+Blockchain Interoperability',
    '+IoT Analytics',
    '+Data Visualization Tools',
    '+Edge Computing Security',
    '+AI for Accessibility',
    '+E-commerce Platforms',
    '+API Integration Strategies',
    '+Cloud Cost Optimization',
    '+AI-driven Personalization',
    '+Neuromorphic Computing',
    '+IoT Sensors',
    '+Serverless Architecture',
    '+Quantum Internet',
    '+AR/VR in Healthcare',
    '+Blockchain Scalability',
    '+AI in Legal Tech',
    '+Edge AI Devices',
    '+Ethical AI Guidelines',
    '+Biometric Authentication',
    '+Data Anonymization Techniques',
    '+IoT in Smart Transportation',
    '+AI in Content Creation',
    '+Quantum Algorithms',
    '+Cybersecurity Training',
    '+Fintech Partnerships',
    '+Blockchain Governance',
    '+AI in Music',
    '+AR/VR Content Creation',
    '+Edge Computing Applications',
    '+AI-powered Robotics',
    '+IoT and Predictive Maintenance',
    '+Cloud Migration Strategies',
    '+Cryptocurrency Adoption',
    '+AI-powered Translation Services',
    '+Blockchain Tokenization',
    '+IoT Security Standards',
    '+Quantum Computing Risks',
    '+AR/VR in Architecture',
    '+Edge Computing Frameworks',
    '+AI Bias Mitigation',
    '+E-commerce Security',
    '+API Security Best Practices',
    '+Cloud Governance Models',
    '+AI in Agriculture',
    '+Blockchain Use Cases',
    '+IoT in Retail',
    '+Data Monetization Strategies',
    '+Quantum-resistant Cryptography',
    '+AR/VR for Training',
    '+Edge AI Chips',
    '+AI-powered Drug Discovery',
    '+IoT in Energy Management',
    '+Cloud Backup Solutions',
    '+Cryptocurrency Investments',
    '+AI-powered Personal Assistants',
    '+Blockchain and Identity Management',
    '+IoT in Smart Cities',
    '+Data Warehousing Technologies',
    '+Quantum Computing Applications',
    '+AR/VR in Marketing',
    '+Edge Computing Use Cases',
    '+AI in Customer Service',
    '+Blockchain Traceability',
    '+IoT Connectivity Solutions',
    '+Cloud Security Standards',
    '+AI in Gaming',
    '+Ethical Data Use',
    '+Biometric Data Protection',
    '+Data Science in Healthcare',
    '+Quantum Computing Hardware',
    '+AR/VR in Tourism',
    '+Edge Computing Challenges',
    '+AI-powered Supply Chain Management',
    '+Blockchain and Smart Contracts',
    '+IoT Fleet Management',
    '+Cloud Automation Tools',
    '+Cryptocurrency Regulations',
    '+AI in Journalism',
    '+Blockchain in Food Traceability',
    '+IoT and Environmental Monitoring',
    '+Data Governance Frameworks',
    '+Quantum Cryptography Challenges',
    '+AR/VR in Retail',
    '+Edge Computing Security Measures',
    '+AI in Human Resources',
    '+Blockchain Privacy Solutions',
    '+IoT and Smart Home Devices',
    '+Cloud-Native Security',
    '+AI-driven Healthcare Diagnosis',
    '+Ethical AI in Finance',
    '+Biometric Data Usage Regulations',
    '+Data Science for Social Good',
    '+Quantum Computing Algorithms',
    '+AR/VR in Entertainment',
    '+Edge AI in Manufacturing',
    '+AI in Cybersecurity',
    '+Blockchain Scalability Solutions',
    '+IoT Device Management',
    '+Cloud Cost Management',
    '+AI in Personal Finance',
    '+Blockchain in Legal Industry',
    '+IoT and Supply Chain Optimization',
    '+Data Privacy Compliance',
    '+Quantum Cryptography Advancements',
    '+AR/VR in Sports',
    '+Edge Computing in Healthcare',
    '+AI-driven Retail Solutions',
    '+Blockchain for Intellectual Property',
    '+IoT and Fleet Tracking',
    '+Cloud-Native Data Storage',
    '+AI-powered Accessibility Tools',
    '+Blockchain Identity Verification',
    '+IoT Security Solutions',
    '+Data Sovereignty Laws',
    '+Quantum Computing Security',
    '+AR/VR in Museums',
    '+Edge Computing in Finance',
    '+AI in Recruitment',
    '+Blockchain Voting Systems',
    '+IoT Wearable Devices',
    '+Cloud-Native Development',
    '+AI in Mental Health',
    '+Blockchain Traceability Solutions',
    '+IoT and Smart Agriculture',
    '+Data Privacy Impact Assessment',
    '+Quantum',
  ]